dist: trusty
language: python

python:
    - 2.7
    - 3.4
    - 3.5
    - 3.6

jdk:
    - openjdk7

install:
    - wget http://apache.mirror.gtcomm.net/spark/spark-2.3.1/spark-2.3.1-bin-hadoop2.7.tgz
    - tar -xzf spark-2.3.1-bin-hadoop2.7.tgz
    - sudo apt-get install pandoc
    - pip install pypandoc coveralls pytest pycodestyle pyspark nibabel nipype

script:
    - export SPARK_HOME=`pwd`/spark-2.3.1-bin-hadoop2.7
    - export PYTHONPATH=$SPARK_HOME/python:$PYTHONPATH
    - export PYTHONPATH=$SPARK_HOME/python/lib/py4j-0.10.7-src.zip:$PYTHONPATH
    - sudo cp pipelines/increment.py /bin
    - pycodestyle pipelines/spark_inc.py tests/test_inc.py
    - pytest -q tests/test_inc.py

after_success:
    - coveralls
